name: 'GitHub Actions Weather Bot'
 
on:
  push:
  schedule:
      # 这里的时间是国际标准时间，需要 减去 16
      # 每天 6.30 执行任务
    - cron: '30 22 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 天气预报 (${{env.REPORT_DATE}})
          html_body: file://index.html
          # body: file://result.png
          to: 727040141@qq.com
          from: GitHub Actions
          content_type: html_body
          attachments: file://result.png
          # content_type: image/png
          # attachments: 
          #   - 
          #     filename: 'result.png'
          #     path: 'file://result.png'
          #     cid: 00000001